title: Yet another blog
email: gabriel.giovanini@pm.me
description: >-
  Gabriel Giovanini's blog.
baseurl: ""
url: "https://gabrielgio.com.br"
twitter_username: giovaninigabs
github_username:  gabrielgio

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

