baseURL = "https://gabrielgio.me/"
languageCode = "en-us"
title = "Yet Another blog"
theme = "flamingo"
enableGitInfo = true

[author]
    name = "Gabriel Giovanini"
    email = "gabriel.giovanini@pm.me"
